# Экзаменационное проектное задание

## Шкала оценивания

- **Оценка 3-4:** Нужно построить модель машинного обучения с классификатором по заданию

- **Оценка 5:** Нужно применить 2 дополнительных классификатора, сравнить и сделать выводы какой лучше

# Часть I. Подготовка набора данных: Отзывы об операторах сотовой связи

## Задание

Вам предлагается выполнить подготовку набора данных

Описание набора данных: Сообщения пользователей в социальных сетях. Целевая переменная - название сотового оператора. Задача построить классификатор для определения о каком сотовом операторе идет речь в сообщении

Ссылка на набор данных для использования в блокноте: https://raw.githubusercontent.com/yakushinav/mo2025/refs/heads/main/data/telecom01.csv

#### 1. Подключение библиотек

In [10]:
# Ваш код здесь
import pandas as pd

#### 2. Чтение набора данных

In [17]:
# Ваш код здесь


url = 'https://raw.githubusercontent.com/yakushinav/mo2025/refs/heads/main/data/telecom01.csv'
data = pd.read_csv(url, index_col=0)

print(data.info())

<class 'pandas.core.frame.DataFrame'>
Index: 7618 entries, 0 to 7617
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   phrase   7618 non-null   object
 1   telecom  7618 non-null   object
dtypes: object(2)
memory usage: 178.5+ KB
None

#### 3. Первые 7 строк набора данных

In [18]:
# Ваш код здесь
data.head(7)

                                              phrase     telecom
0  @mkomov Максим, Вашем письмо мы получили. Наши...     beeline
1     «Мегафон» стал владельцем 50% акций «Евросети»     megafon
2   МТС Россия прислала жителям Херсонщины сообщения         mts
3  ВИДЕО: http://t.co/PSMLAhR4fI Реклама со смехо...         mts
4  @parfenov1960 потому что МТС достало, а пчел н...         mts
5  На Дне города в Тюмени «МегаФон» разыграет сма...     megafon
6  &amp;laquo;Ростелеком&amp;raquo; стал партнеро...  rostelecom

#### 4. Последние 5 строк набора данных

In [19]:
# Ваш код здесь
data.tail(5)

                                                 phrase telecom
7613                   @iNikkiiiii подать в суд на МТС      mts
7614  Ну если-же это МТС,то скорость интернета будет...     mts
7615  RT @Olympialeigh: У МТС проблемы со связью из-...     mts
7616  RT @ManisaMerkez45: У МТС проблемы со связью и...     mts
7617  RT @MertKaraoban: У МТС проблемы со связью из-...     mts

#### 5. Поля набора данных

In [20]:
# Ваш код здесь
print(data.columns)

Index(['phrase', 'telecom'], dtype='object')

#### 6. Размер набора данных (количество полей и строк)

In [21]:
# Ваш код здесь
data.shape

(7618, 2)

#### 7. Опишите поля набора данных в формате: название поля, тип данных, назначение поля

phrase - текст сообщения пользователя,
telecom - оператор сотовой связи

#### 8. Информация о наборе данных

In [27]:
# Ваш код здесь
print(data.info())

<class 'pandas.core.frame.DataFrame'>
Index: 7618 entries, 0 to 7617
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   phrase   7618 non-null   object
 1   telecom  7618 non-null   object
dtypes: object(2)
memory usage: 178.5+ KB
None

#### 9. Проверка наличия пропусков в данных

In [25]:
# Ваш код здесь
data.isna().sum()

phrase     0
telecom    0
dtype: int64

#### 10. Если вы обнаружили пропуски в данных, то удалите их

In [26]:
# Ваш код здесь
data["telecom"].value_counts()

telecom
beeline       3120
mts           2825
megafon        990
rostelecom     402
tele2          268
skylink         10
komstar          3
Name: count, dtype: int64

#### 11. Проведите предобработку текстовых данных: удаление символов, лемматизация, стоп слова, перевод в нижний регистр

In [29]:
!pip install pymystem3

Collecting pymystem3
  Downloading pymystem3-0.2.0-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from pymystem3) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->pymystem3) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->pymystem3) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->pymystem3) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->pymystem3) (2026.5.20)
Downloading pymystem3-0.2.0-py3-none-any.whl (10 kB)
Installing collected packages: pymystem3
Successfully installed pymystem3-0.2.0

In [30]:
import re
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from pymystem3 import Mystem

In [35]:
# Ваш код здесь
# Загрузка стоп-слов для русского языка
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

# Инициализация Mystem
mystem = Mystem()

# Функция для предобработки текста
def preprocess_text(text):
    # Приведение к нижнему регистру
    text = text.lower()

    # Удаление пунктуации и цифр
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\d+', '', text)

    # Токенизация текста
    tokens = word_tokenize(text, language='russian')

    # Удаление стоп-слов
    stop_words = set(stopwords.words('russian'))
    tokens = [word for word in tokens if word not in stop_words]

    # Лемматизация с использованием Mystem
    lemmas = mystem.lemmatize(' '.join(tokens))
    lemmas = [lemma.strip() for lemma in lemmas if lemma.strip()]

    return ' '.join(lemmas)

data['processed_review'] = data['phrase'].apply(preprocess_text)

data.head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

,phrase,telecom,processed_review
0,"@mkomov Максим, Вашем письмо мы получили. Наши...",beeline,mkomov максим ваш письмо получать наш сотрудни...
1,«Мегафон» стал владельцем 50% акций «Евросети»,megafon,мегафон становиться владелец акция евросеть
2,МТС Россия прислала жителям Херсонщины сообщения,mts,мтс россия присылать житель херсонщина сообщение
3,ВИДЕО: http://t.co/PSMLAhR4fI Реклама со смехо...,mts,видео httptcopsmlahrfi реклама смех мтс супер
4,"@parfenov1960 потому что МТС достало, а пчел н...",mts,parfenov мтс доставать пчела ненавидеть детств...

#### 12. Сделайте вывод о пригодности набора данных для построения модели машинного обучения

Набор данных подходит для задачи классификации Данные содержат текст сообщений и целевой класс telecom. После предобработки тексты можно использовать для машинного обучения.

# Часть II. Построение модели машинного обучения для набора данных: Отзывы об операторах сотовой связи

## Задание

Вам нужно решить задачу классификации с помощью алгоритма

Метод К-ближайших соседей KNeighborsClassifier



Целевая переменная, результат: **telecom**

#### 13. Разделить выборку на признаки (Х) и результат (Y)

In [44]:
# Ваш код здесь
from sklearn.model_selection import train_test_split
X = data['processed_review']
Y = data['telecom']

#### 14. Разделить на обучающую и тестовую выборки

In [46]:
# Ваш код здесь
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

print(x_train.shape)
print(x_test.shape)

(5104,)
(2514,)

#### 15. TF-IDF векторизация и мешок слов

In [53]:
# Ваш код здесь

from sklearn.neighbors import KNeighborsClassifier
#Векторизация текста
from sklearn.feature_extraction.text import CountVectorizer

from nltk import ngrams

In [52]:
vec = CountVectorizer(ngram_range=(1, 1)) #строим BoW для слов
bow = vec.fit_transform(x_train) #преобразуем обучающие данные

#### 16. Сформировать модель машинного обучения

In [54]:
# Ваш код здесь

clf = KNeighborsClassifier(n_neighbors=5)

#### 17. Обучить модель

In [55]:
# Ваш код здесь
clf.fit(bow, y_train)

KNeighborsClassifier()

#### 18. Оценить качество модели

In [60]:
from sklearn.metrics import accuracy_score, classification_report

# преобразуем тестовые данные
x_test_bow = vec.transform(x_test)
y_pred = clf.predict(x_test_bow)

# точность модели
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9478918058870326
              precision    recall  f1-score   support

     beeline       0.92      0.97      0.95      1061
     komstar       0.00      0.00      0.00         1
     megafon       0.98      0.88      0.93       335
         mts       0.96      0.98      0.97       907
  rostelecom       1.00      0.85      0.92       123
     skylink       0.00      0.00      0.00         4
       tele2       0.97      0.77      0.86        83

    accuracy                           0.95      2514
   macro avg       0.69      0.64      0.66      2514
weighted avg       0.95      0.95      0.95      2514

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

#### 19. Выполнить предсказание класса для трех разных фраз

In [67]:
phrases = [
    'У меня плохо работает интернет от МТС',
    'Билайн опять списал деньги',
    'Ростелеком радует качеством связи'
]

phrases_processed = [preprocess_text(text) for text in phrases]

phrases_vectorized = vec.transform(phrases_processed)

predictions = clf.predict(phrases_vectorized)

for phrase, pred in zip(phrases, predictions):
    print(phrase)
    print(pred)

У меня плохо работает интернет от МТС
mts
Билайн опять списал деньги
beeline
Ростелеком радует качеством связи
rostelecom

#### 20. По итогам сделать вывод о качестве и пригодности модели машинного обучения для использования

Модель машинного обучения успешно классифицирует отзывы пользователей по операторам сотовой связи. Модель способна определять оператора связи по тексту сообщения. Качество зависит от предобработки текста и объема обучающих данных.

#### 21. Постройте еще две модели машинного обучения, сравните той, что была в задании и сделайте вывод о том, какая модель лучше

In [69]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

In [78]:
#Logistic Regression

lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(bow, y_train)
lr_pred = lr_model.predict(x_test_bow)
print(accuracy_score(y_test, lr_pred))

print(classification_report(y_test, lr_pred))

0.9801113762927606
              precision    recall  f1-score   support

     beeline       0.98      0.99      0.98      1061
     komstar       0.00      0.00      0.00         1
     megafon       0.98      0.96      0.97       335
         mts       0.97      0.99      0.98       907
  rostelecom       1.00      0.93      0.97       123
     skylink       0.00      0.00      0.00         4
       tele2       0.95      0.96      0.96        83

    accuracy                           0.98      2514
   macro avg       0.70      0.69      0.70      2514
weighted avg       0.98      0.98      0.98      2514

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [84]:
# Проверка работы Logistic Regression на конкретных примерах

from sklearn.feature_extraction.text import CountVectorizer

count_vec = CountVectorizer(ngram_range=(1,1))

bow = count_vec.fit_transform(x_train)

x_test_bow = count_vec.transform(x_test)

examples = ["МТС постоянно присылает рекламу и навязывает услуги",
    "Билайн радует быстрым интернетом",
    "Мегафон плохо ловит связь в метро"]

examples_processed = [preprocess_text(text) for text in examples]

examples_vectorized = count_vec.transform(examples_processed)

predictions = lr_model.predict(examples_vectorized)


for text, pred in zip(examples, predictions):
    print(text)
    print(pred)

МТС постоянно присылает рекламу и навязывает услуги
mts
Билайн радует быстрым интернетом
beeline
Мегафон плохо ловит связь в метро
megafon

In [76]:
#Naive Bayes

nb_model = MultinomialNB()
nb_model.fit(bow, y_train)
nb_pred = nb_model.predict(x_test_bow)
nb_acc = accuracy_score(y_test, nb_pred)

print(nb_acc)
print(classification_report(y_test, nb_pred))

0.9160700079554495
              precision    recall  f1-score   support

     beeline       0.86      0.99      0.92      1061
     komstar       0.00      0.00      0.00         1
     megafon       0.98      0.70      0.82       335
         mts       0.96      0.96      0.96       907
  rostelecom       0.98      0.73      0.84       123
     skylink       0.00      0.00      0.00         4
       tele2       0.98      0.70      0.82        83

    accuracy                           0.92      2514
   macro avg       0.68      0.58      0.62      2514
weighted avg       0.92      0.92      0.91      2514

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [83]:
# Проверка работы модели Naive Bayes на конкретных примерах

examples = ["МТС постоянно присылает рекламу и навязывает услуги",
    "Билайн радует быстрым интернетом",
    "Мегафон плохо ловит связь в метро"]

examples_processed = [preprocess_text(text) for text in examples]

examples_vectorized = count_vec.transform(examples_processed)
nb_predictions = nb_model.predict(examples_vectorized)

for text, pred in zip(examples, nb_predictions):
    print(text)
    print(pred)

МТС постоянно присылает рекламу и навязывает услуги
mts
Билайн радует быстрым интернетом
beeline
Мегафон плохо ловит связь в метро
megafon

В ходе работы были построены три модели машинного обучения: KNeighborsClassifier, Logistic Regression и Naive Bayes.
После сравнения точности моделей оказалось, что Logistic Regression показала лучший результат классификации текстов.